settings/urls.py
# coding: utf-8
"""intercater URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from catalog.models import Catalog
from config.models import init_config

config = init_config()
settings.GRAPPELLI_ADMIN_TITLE = settings.SITE_NAME = config['site_name']

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^%s' % settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^mailer/', include('mailer.urls')),
    url(r'^customer/', include('customer.urls', namespace="customer")),
    url(r'^%s/' % settings.API_URL.strip('/'), include('settings.api')),
    url(r'^%s/' % Catalog.full_path_prefix.strip('/'), include('catalog.urls')),
    url(r'^/?', include('section.urls', namespace="section")),
]

src/customer/urls.py
from django.conf.urls import include, url
from .views import DefaultView

urlpatterns = (
    url(r'^$', DefaultView.as_view(), name='default'),
)

templates/layouts/base.html
<!doctype html>
<html lang="ru">
{% load staticfiles common common_attachments product cache %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ seo.description }}">
    <meta name="keywords" content="{{ seo.keywords }}">
    <title>{{ seo.title }}</title>

    {% block css %}
        <link rel="stylesheet" href="{% static 'vendor/uikit/css/uikit.almost-flat.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'vendor/uikit/css/components/slider.almost-flat.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'vendor/uikit/css/components/slidenav.almost-flat.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/catalog.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/basket.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/customer.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/sections.css' %}"/>
    {% endblock %}
</head>

<body ng-app="Site" ng-controller="Base" class="uk-height-1-1">
{% cache settings.CACHE_TIME header request.path %}
    <nav class="topest-menu">
        <div class="uk-container uk-container-center">
            <ul class="uk-list uk-float-left">
                <li>
                    <a href="/" class="{{ 'active'|equals_path_class:'/' }}"><i class="uk-icon-home"></i> Главная</a>
                </li>

                {% for menu in top_menu %}
                    <li>
                        <a href="{{ menu.get_full_path }}"
                           class="{{ 'active'|active_path_class:menu.get_full_path }}">
                            <i class="uk-icon-{{ menu.name }}"></i> {{ menu.title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <ul class="uk-list uk-float-right right-menu" ng-hide="customer.email" ng-cloak>
                <li>
                    <a href="{% url 'customer:default' %}#/signup/">
                        <i class="uk-icon-user"></i>
                        <span class="uk-visible-large">регистрация</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'customer:default' %}#/signin/">
                        <i class="uk-icon-sign-in"></i>
                        <span class="uk-visible-large">вход</span>
                    </a>
                </li>
            </ul>

            <ul class="uk-list uk-float-right right-menu" ng-show="customer.email" ng-cloak>
                <li>
                    <a href="{% url 'customer:default' %}#/orders/">
                        <i class="uk-icon-user"></i>
                        <span class="uk-visible-large" ng-bind="customer.name"></span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <header class="site-header">
        <div class="uk-container uk-container-center">
        <span class="site-logo uk-float-left">
            {% include 'includes/logo.html' %}
        </span>

            <div class="float-right">
                <ul class="contact-info">
                    <li class="contact-block">
                        <span class="uk-icon-phone label uk-hidden-small"></span>

                        <ul class="uk-list uk-display-inline-block contact-data">
                            {% for phone in config.phones %}
                                <li>{{ phone }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="contact-block">
                        <span class="uk-icon-envelope label uk-hidden-small"></span>

                        <ul class="uk-list uk-display-inline-block contact-data">
                            {% for email in config.emails %}
                                <li>{{ email }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <nav class="catalog-menu" data-uk-sticky>
        <div class="uk-container uk-container-center">
            <ul class="uk-list uk-display-inline-block uk-float-left">
                <li class="{{ 'active'|active_path_class:catalog_section.get_full_path }}"><a
                        href="{{ catalog_section.get_full_path }}">{{ catalog_section.title }}</a></li>
                {% for cat in category_product %}
                    <li class="{{ 'active'|active_path_class:cat.get_full_path }}"><a
                            href="{{ cat.get_full_path }}">{{ cat.title }}</a></li>
                {% endfor %}
            </ul>

            <form class="uk-form uk-float-right">
                <div class="uk-form-icon">
                    <i class="uk-icon-search"></i>
                    <input type="search" placeholder="Поиск...">
                </div>
            </form>

            <div class="uk-float-right" ng-controller="Cart">
                <div class="cart-info">
                    <a href="{{ cart_section.get_full_path }}">
                        <i class="uk-icon-shopping-cart"></i>
                        товаров: <span class="goods-count" ng-bind="cart.length"></span> шт. <span
                            ng-bind-html="sum() | rub"></span>
                    </a>
                </div>
            </div>
        </div>
    </nav>
{% endcache %}

{% block top-content %}{% endblock %}

<div class="uk-container uk-container-center">
    {% block content-base %}{% endblock %}
</div>

{% block pre_footer %}{% endblock %}

{% cache settings.CACHE_TIME footer %}
    <footer class="site-footer">
        <div class="uk-container uk-container-center">
            <div class="uk-grid sub-info">
                <div class="uk-width-medium-1-3 uk-width-1-1">
                    <div class="site-logo">
                        {% include 'includes/logo.html' %}
                    </div>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis distinctio, dolore, dolorem
                        doloribus fugit id modi nesciunt non</p>

                    <ul>
                        <li>+7 921 927 43 33</li>
                        <li>+7 921 927 43 33</li>
                    </ul>

                    <ul>
                        <li>degacth@yandex.ru</li>
                        <li>degacth@yandex.ru</li>
                    </ul>

                    <i class="uk-icon-button uk-icon-vk"></i>
                    <i class="uk-icon-button uk-icon-facebook"></i>
                    <i class="uk-icon-button uk-icon-github"></i>
                </div>

                <div class="uk-width-medium-2-3 uk-width-1-1">
                    <div class="big-title">Последние просмотренные товары</div>

                    <ul class="uk-grid uk-grid-width-1-1 uk-grid-width-small-1-2 uk-grid-width-medium-1-3"
                        ng-controller="LastProducts">
                        {% verbatim %}
                            <li ng-repeat="product in last_products">
                                <div class="item">
                                    <div class="uk-grid">
                                        <div class="uk-width-1-3">
                                            <a href="{{ product.get_full_path }}"
                                               ng-bind-html="product.get_thumbnail_tag | html"></a>
                                        </div>
                                        <div class="uk-width-2-3 last-prod-item">
                                            <div class="title" ng-bind="product.title"></div>
                                            <div class="price" ng-bind-html="product.get_price | rub"></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endverbatim %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="sub-footer">
            <div class="uk-container uk-container-center">
                Сайт не содержит ГМО, консерванов и PHP кода, только <span class="base-pink"><span class="base-pink"
                                                                                                   title="Django">Python</span> и <span
                    class="base-pink" title="Angular, Underscore">CoffeeScript</span></span>
            </div>
        </div>
    </footer>
{% endcache %}

{% block js %}
    {% include 'includes/ng_config.html' %}

    <script src="{% static 'vendor/underscore/underscore-min.js' %}"></script>
    <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/uikit/js/uikit.min.js' %}"></script>
    <script src="{% static 'vendor/uikit/js/components/sticky.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>

    <script src="{% static 'vendor/angular/angular.min.js' %}"></script>
    <script src="{% static 'vendor/angular-resource/angular-resource.min.js' %}"></script>
    <script src="{% static 'vendor/angular-route/angular-route.min.js' %}"></script>
    <script src="{% static 'vendor/angular-recaptcha/release/angular-recaptcha.min.js' %}"></script>

    <script src="{% static 'js/app/site/SiteApp.js' %}"></script>
    <script src="{% static 'js/app/site/Controller.js' %}"></script>

    <script src="{% static 'catalog/js/CatalogApp.js' %}"></script>
    <script src="{% static 'catalog/js/Services.js' %}"></script>
    <script src="{% static 'catalog/js/Controller.js' %}"></script>

    <script src="{% static 'customer/js/CustomerApp.js' %}"></script>
    <script src="{% static 'customer/js/Controllers.js' %}"></script>
    <script src="{% static 'customer/js/Services.js' %}"></script>

    <script src="{% static 'feedback/js/FeedbackApp.js' %}"></script>
{% endblock %}

</body>

</html>

templates/layouts/content.html
{% extends 'layouts/base.html' %}
{% load common %}

{% block content-base %}
    {% block breadcrumbs %}
        <ul class="breadcrumbs uk-list uk-float-right">
            {% for crumb in seo.breadcrumbs %}
                <li>
                    {% if not forloop.last %}
                        <a href="{{ crumb.path }}">{{ crumb.title }}</a> <i class="uk-icon-chevron-right"></i>
                    {% else %}
                        <span>{{ crumb.title }}</span>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endblock %}

    <h1>{{ current.title }} {% admin_edit current %}</h1>

    {% block content %}{% endblock %}
{% endblock %}

templates/layouts/two-col-content.html
{% extends 'layouts/content.html' %}

{% block content %}
    <div class="uk-grid" {% block content-attrs %}{% endblock %}>
        <div class="uk-width-1-1 uk-width-medium-1-3 uk-width-large-1-4 uk-margin-bottom">
            {% block sidebar %}{% endblock %}
        </div>

        <div class="uk-width-1-1 uk-width-medium-2-3 uk-width-large-3-4">
            {% block content-bar %}{% endblock %}
        </div>
    </div>
{% endblock %}